# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints_vga.xdc

# Block Designs: bd/pong_bd/pong_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd || ORIG_REF_NAME==pong_bd} -quiet] -quiet

# IP: bd/pong_bd/ip/pong_bd_vga_controller_0_0/pong_bd_vga_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd_vga_controller_0_0 || ORIG_REF_NAME==pong_bd_vga_controller_0_0} -quiet] -quiet

# IP: bd/pong_bd/ip/pong_bd_image_source_0_0/pong_bd_image_source_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd_image_source_0_0 || ORIG_REF_NAME==pong_bd_image_source_0_0} -quiet] -quiet

# IP: bd/pong_bd/ip/pong_bd_processing_system7_0_0/pong_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd_processing_system7_0_0 || ORIG_REF_NAME==pong_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/pong_bd/ip/pong_bd_rst_ps7_0_100M_0/pong_bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==pong_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/pong_bd/ip/pong_bd_ps7_0_axi_periph_0/pong_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==pong_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pong_bd/ip/pong_bd_axi_gpio_0_0/pong_bd_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd_axi_gpio_0_0 || ORIG_REF_NAME==pong_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/pong_bd/ip/pong_bd_xbar_0/pong_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd_xbar_0 || ORIG_REF_NAME==pong_bd_xbar_0} -quiet] -quiet

# IP: bd/pong_bd/ip/pong_bd_axi_gpio_1_0/pong_bd_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd_axi_gpio_1_0 || ORIG_REF_NAME==pong_bd_axi_gpio_1_0} -quiet] -quiet

# IP: bd/pong_bd/ip/pong_bd_pong_vga_regs_0_0/pong_bd_pong_vga_regs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd_pong_vga_regs_0_0 || ORIG_REF_NAME==pong_bd_pong_vga_regs_0_0} -quiet] -quiet

# IP: bd/pong_bd/ip/pong_bd_auto_pc_0/pong_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pong_bd_auto_pc_0 || ORIG_REF_NAME==pong_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/pong_bd/ip/pong_bd_processing_system7_0_0/pong_bd_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pong_bd_processing_system7_0_0 || ORIG_REF_NAME==pong_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pong_bd/ip/pong_bd_rst_ps7_0_100M_0/pong_bd_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pong_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==pong_bd_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pong_bd/ip/pong_bd_rst_ps7_0_100M_0/pong_bd_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pong_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==pong_bd_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pong_bd/ip/pong_bd_rst_ps7_0_100M_0/pong_bd_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/pong_bd/ip/pong_bd_axi_gpio_0_0/pong_bd_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pong_bd_axi_gpio_0_0 || ORIG_REF_NAME==pong_bd_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pong_bd/ip/pong_bd_axi_gpio_0_0/pong_bd_axi_gpio_0_0_ooc.xdc

# XDC: bd/pong_bd/ip/pong_bd_axi_gpio_0_0/pong_bd_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pong_bd_axi_gpio_0_0 || ORIG_REF_NAME==pong_bd_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pong_bd/ip/pong_bd_xbar_0/pong_bd_xbar_0_ooc.xdc

# XDC: bd/pong_bd/ip/pong_bd_axi_gpio_1_0/pong_bd_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pong_bd_axi_gpio_1_0 || ORIG_REF_NAME==pong_bd_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pong_bd/ip/pong_bd_axi_gpio_1_0/pong_bd_axi_gpio_1_0_ooc.xdc

# XDC: bd/pong_bd/ip/pong_bd_axi_gpio_1_0/pong_bd_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pong_bd_axi_gpio_1_0 || ORIG_REF_NAME==pong_bd_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pong_bd/ip/pong_bd_auto_pc_0/pong_bd_auto_pc_0_ooc.xdc

# XDC: bd/pong_bd/pong_bd_ooc.xdc
