# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Projects/pong_vga/pong_vga.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Projects/pong_vga/pong_vga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths C:/Xilinx/vivado-boards/new/board_files [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo c:/Xilinx/Projects/pong_vga/pong_vga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Xilinx/Projects/Pong_Game/VGA_Controller.vhd
  C:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/new/image_source.vhd
  C:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/imports/pong_vga/pong_vga_regs_pkg.vhd
  C:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/imports/pong_vga/pong_vga_regs.vhd
  C:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/hdl/pong_bd_wrapper.vhd
}
add_files C:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/pong_bd.bd
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_processing_system7_0_0/pong_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_rst_ps7_0_100M_0/pong_bd_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_rst_ps7_0_100M_0/pong_bd_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_rst_ps7_0_100M_0/pong_bd_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_axi_gpio_0_0/pong_bd_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_axi_gpio_0_0/pong_bd_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_axi_gpio_0_0/pong_bd_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_xbar_0/pong_bd_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_axi_gpio_1_0/pong_bd_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_axi_gpio_1_0/pong_bd_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_axi_gpio_1_0/pong_bd_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/ip/pong_bd_auto_pc_0/pong_bd_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Xilinx/Projects/pong_vga/pong_vga.srcs/sources_1/bd/pong_bd/pong_bd_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/Projects/pong_vga/pong_vga.srcs/constrs_1/new/constraints_vga.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Projects/pong_vga/pong_vga.srcs/constrs_1/new/constraints_vga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top pong_bd_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pong_bd_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pong_bd_wrapper_utilization_synth.rpt -pb pong_bd_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
